#! /usr/bin/env python3
from subprocess import run
import sys

name = sys.argv[-1]
args = ["vim", "-O", f"include/{name}.hpp"]
if len(sys.argv) == 3:
    assert sys.argv[1] in ["--header", "-h"], "The only supported option is `--header`, aka `-h`."
elif len(sys.argv) == 2:
    args.append(f"libhexed/{name}.cpp")
else:
    raise Exception(f"`cpp-open` takes 1 or 2 arguments.")
args.append(f"test/test_{name}.cpp")
run(args)
